#!/usr/bin/env bun
/**
 * Walks `client/dist/` and generates
 * `service/src/generated/client-assets.ts` so that `bun build --compile`
 * bakes every client asset into the resulting binary.
 *
 * Each asset is imported via Bun's file-type import syntax
 * (`import x from "./path" with { type: "file" }`). At compile time Bun
 * embeds the file bytes into the binary; at runtime the import returns
 * a file path that Bun.file() can read transparently from the embedded
 * bundle (or from disk when not compiled).
 *
 * Invocation:
 *   bun run scripts/embed-assets.ts
 *
 * Prerequisite: `cd client && bun run build` must have produced
 * `client/dist/`. The script exits with code 1 if the dist tree is
 * missing so you can't accidentally produce a binary that serves an
 * empty client.
 */
import { readdirSync, statSync, existsSync, writeFileSync } from "node:fs";
import { join, relative, sep, posix } from "node:path";

const REPO_ROOT = new URL("..", import.meta.url).pathname;
const CLIENT_DIST = join(REPO_ROOT, "client", "dist");
const OUTPUT = join(REPO_ROOT, "service", "src", "generated", "client-assets.ts");
const OUTPUT_DIR = join(REPO_ROOT, "service", "src", "generated");

if (!existsSync(CLIENT_DIST)) {
  console.error(`[embed-assets] client/dist not found — run \`cd client && bun run build\` first.`);
  process.exit(1);
}

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      out.push(...walk(full));
    } else {
      out.push(full);
    }
  }
  return out;
}

const files = walk(CLIENT_DIST).sort();
if (files.length === 0) {
  console.error(`[embed-assets] client/dist is empty.`);
  process.exit(1);
}

// Build-time import path for the generated module is relative to
// service/src/generated/, going up three levels to the repo root.
const IMPORT_PREFIX = "../../../client/dist";

type Entry = { urlPath: string; importPath: string; identifier: string };

const entries: Entry[] = files.map((full, idx) => {
  const rel = relative(CLIENT_DIST, full).split(sep).join(posix.sep);
  const urlPath = "/" + rel;
  const importPath = `${IMPORT_PREFIX}/${rel}`;
  // Legal JS identifier derived from the index + a short slug.
  const slug = rel.replace(/[^a-zA-Z0-9]+/g, "_").slice(0, 32);
  const identifier = `_a${idx}_${slug}`;
  return { urlPath, importPath, identifier };
});

const lines: string[] = [];
// Auto-generated code opts out of typechecking: the `with { type: "file" }`
// imports return Bun-specific types that tsc doesn't resolve (HTMLBundle,
// module-not-found for .css/.png/.svg), and this file has no human author
// to reason about those types. The committed stub version of this file
// is pure TypeScript and does not need @ts-nocheck.
lines.push("// @ts-nocheck");
lines.push("/**");
lines.push(" * AUTO-GENERATED by scripts/embed-assets.ts. Do not edit by hand.");
lines.push(" * Each entry uses Bun's file-type import so `bun build --compile`");
lines.push(" * embeds the asset bytes into the final binary.");
lines.push(" */");
for (const e of entries) {
  lines.push(`import ${e.identifier} from "${e.importPath}" with { type: "file" };`);
}
lines.push("");
lines.push("export const CLIENT_ASSETS: Record<string, string> = {");
for (const e of entries) {
  lines.push(`  ${JSON.stringify(e.urlPath)}: ${e.identifier},`);
}
// Alias `/` to the root index.html so the server can handle the bare path.
const rootIndex = entries.find((e) => e.urlPath === "/index.html");
if (rootIndex) {
  lines.push(`  "/": ${rootIndex.identifier},`);
}
lines.push("};");
lines.push("");

if (!existsSync(OUTPUT_DIR)) {
  console.error(`[embed-assets] output directory missing: ${OUTPUT_DIR}`);
  process.exit(1);
}

writeFileSync(OUTPUT, lines.join("\n"));

const bytes = files.reduce((sum, f) => sum + statSync(f).size, 0);
console.log(
  `[embed-assets] wrote ${entries.length} entries (${(bytes / 1024).toFixed(1)} KB) to ${relative(REPO_ROOT, OUTPUT)}`
);
